### ISSUE TITLE
examples fail

### ISSUE THREAD

**Issue by paultag** [Guggenheim-Helsinki/Data-API#1]
the example `jpg` in the README 404s

In particular, [this one](https://s3-us-west-2.amazonaws.com/api.designguggenheimhelsinki.org/v1/data/GH-03631231/GH-03631231-partC1.jpg) breaks

**Comment by paultag** [comment]
perhaps change it out with [this one](https://s3-us-west-2.amazonaws.com/api.designguggenheimhelsinki.org/v1/data/v1/GH-8518347283/GH-8518347283-partC1.jpg)

**Comment by troyth** [comment]
Thanks for catching that @paultag !
